#  _    _                                         _     _              _
# | |  | |                          /\           (_)   | |            | |
# | |__| | ___  _ __ ___   ___     /  \   ___ ___ _ ___| |_ __ _ _ __ | |_
# |  __  |/ _ \| '_ ` _ \ / _ \   / /\ \ / __/ __| / __| __/ _` | '_ \| __|
# | |  | | (_) | | | | | |  __/  / ____ \\__ \__ \ \__ \ || (_| | | | | |_
# |_|  |_|\___/|_| |_| |_|\___| /_/    \_\___/___/_|___/\__\__,_|_| |_|\__|
#
# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  # Nome do local onde o Home Assistant está sendo executado
  name: Casa
  # Localização necessária para calcular a hora em que o sol nasce e se põe
  latitude: !secret lat
  longitude: !secret long
  # Impactos meteorológicos / dados do nascer do sol (altitude acima do nível do mar em metros)
  elevation: 1128
  # metric para Metric, imperial para Imperial
  unit_system: metric
  # Escolha o seu aqui: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: !secret base_url
#   api_password: !secret api_password
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem
#   #ip_ban_enabled: True
#   login_attempts_threshold: 3

recorder:
  db_url: mysql://homeassistant:smartcasa@core-mariadb/homeassistant?charset=utf8

# Text to speech
tts:
  - platform: google_translate

# Enables the frontend
#  ______               _                 _
# |  ____|             | |               | |
# | |__ _ __ ___  _ __ | |_ ___ _ __   __| |
# |  __| '__/ _ \| '_ \| __/ _ \ '_ \ / _` |
# | |  | | | (_) | | | | ||  __/ | | | (_| |
# |_|  |_|  \___/|_| |_|\__\___|_| |_|\__,_|
# https://www.home-assistant.io/components/frontend/
frontend:
#  themes: !include themes.yaml
  themes: !include_dir_merge_named themes/

# Sensores
#   _____
#  / ____|
# | (___   ___ _ __  ___  ___  _ __
#  \___ \ / _ \ '_ \/ __|/ _ \| '__|
#  ____) |  __/ | | \__ \ (_) | |
# |_____/ \___|_| |_|___/\___/|_|
sensor: !include sensor.yaml

# Interruptores
#   _____         _ _       _
#  / ____|       (_) |     | |
# | (_____      ___| |_ ___| |__
#  \___ \ \ /\ / / | __/ __| '_ \
#  ____) \ V  V /| | || (__| | | |
# |_____/ \_/\_/ |_|\__\___|_| |_|
# https://www.home-assistant.io/components/switch/
# https://www.home-assistant.io/components/switch.template/
# https://www.home-assistant.io/components/switch.mqtt/
# https://www.home-assistant.io/components/broadlink/
switch: !include switch.yaml

# Binary Sensor
#  ____  _                           _____
# |  _ \(_)                         / ____
# | |_) |_ _ __   __ _ _ __ _   _  | (___   ___ _ __  ___  ___  _ __
# |  _ <| | '_ \ / _` | '__| | | |  \___ \ / _ \ '_ \/ __|/ _ \| '__|
# | |_) | | | | | (_| | |  | |_| |  ____) |  __/ | | \__ \ (_) | |
# |____/|_|_| |_|\__,_|_|   \__, | |_____/ \___|_| |_|___/\___/|_|
#                           |___/
# https://www.home-assistant.io/components/binary_sensor/
# https://www.home-assistant.io/components/binary_sensor.mqtt/
# https://www.home-assistant.io/components/ping/
# https://community.home-assistant.io/t/sonoff-rf-bridge-strategies-for-receiving-data/108181
binary_sensor: !include binary_sensor.yaml

camera:
  - platform: ffmpeg
    name: Camera 1
    input: -rtsp_transport tcp -i rtsp://192.168.0.100:554/user=admin&password=964710&channel=1&stream=0.sdp?

# Inputs de texto
#  _____                   _    _            _
# |_   _|                 | |  | |          | |
#   | |  _ __  _ __  _   _| |_ | |_ _____  _| |_
#   | | | '_ \| '_ \| | | | __|| __/ _ \ \/ / __|
#  _| |_| | | | |_) | |_| | |_ | ||  __/>  <| |_
# |_____|_| |_| .__/ \__,_|\__| \__\___/_/\_\\__|
#             | |           ______
#             |_|          |______|
# https://www.home-assistant.io/components/input_text/
input_text:
  box1:
    name: "Valor kW/h"
    initial: "0.800"

#
#    _____                     _   _______        _   
#   / ____|                   | | |__   __|      | |  
#  | (___  _ __   ___  ___  __| |    | | ___  ___| |_ 
#   \___ \| '_ \ / _ \/ _ \/ _` |    | |/ _ \/ __| __|
#   ____) | |_) |  __/  __/ (_| |    | |  __/\__ \ |_ 
#  |_____/| .__/ \___|\___|\__,_|    |_|\___||___/\__|
#         | |                                         
#         |_|  
speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload

# HACS
#   _    _          _____  _____ 
#  | |  | |   /\   / ____|/ ____|
#  | |__| |  /  \ | |    | (___  
#  |  __  | / /\ \| |     \___ \ 
#  | |  | |/ ____ \ |____ ____) |
#  |_|  |_/_/    \_\_____|_____/ 
# hacs:
#   token: !secret hacs_token
#   theme: true
#   python_script: true

# Informações sobre o sistema e seus componentes. Também permite executar ferramentas de diagnóstico para diagnosticar problemas.
#   _____           _                   _                _ _   _
#  / ____|         | |                 | |              | | | | |
# | (___  _   _ ___| |_ ___ _ __ ___   | |__   ___  __ _| | |_| |__
#  \___ \| | | / __| __/ _ \ '_ ` _ \  | '_ \ / _ \/ _` | | __| '_ \
#  ____) | |_| \__ \ ||  __/ | | | | | | | | |  __/ (_| | | |_| | | |
# |_____/ \__, |___/\__\___|_| |_| |_| |_| |_|\___|\__,_|_|\__|_| |_|
#          __/ |
#         |___/
# https://www.home-assistant.io/components/system_health/
#system_health:

# Grupos
#   _____
#  / ____|
# | |  __ _ __ ___  _   _ _ __
# | | |_ | '__/ _ \| | | | '_ \
# | |__| | | | (_) | |_| | |_) |
#  \_____|_|  \___/ \__,_| .__/
#                        | |
#                        |_|
# https://www.home-assistant.io/components/group/
group: !include groups.yaml

# Automações
#                _                        _   _
#     /\        | |                      | | (_)
#    /  \  _   _| |_ ___  _ __ ___   __ _| |_ _  ___  _ __
#   / /\ \| | | | __/ _ \| '_ ` _ \ / _` | __| |/ _ \| '_ \
#  / ____ \ |_| | || (_) | | | | | | (_| | |_| | (_) | | | |
# /_/    \_\__,_|\__\___/|_| |_| |_|\__,_|\__|_|\___/|_| |_|
# https://www.home-assistant.io/components/automation/
# https://www.home-assistant.io/docs/automation/examples/
# https://www.home-assistant.io/cookbook/
automation: !include automations.yaml

# Scripts
#   _____           _       _
#  / ____|         (_)     | |
# | (___   ___ _ __ _ _ __ | |
#  \___ \ / __| '__| | '_ \| __|
#  ____) | (__| |  | | |_) | |_
# |_____/ \___|_|  |_| .__/ \__|
#                    |_|
# https://www.home-assistant.io/components/script/
# https://www.home-assistant.io/docs/scripts/
script: !include scripts.yaml

# Zonas de localização
#  ______
# |___  /
#    / / ___  _ __   ___
#   / / / _ \| '_ \ / _ \
#  / /_| (_) | | | |  __/
# /_____\___/|_| |_|\___|
# https://www.home-assistant.io/components/zone/
zone: !include zone.yaml

#  _______        _     _                    _____  _____ _____ _____
# |__   __|      | |   | |            /\    / ____|/ ____|_   _|_   _|
#    | | _____  _| |_  | |_ ___      /  \  | (___ | |      | |   | |
#    | |/ _ \ \/ / __| | __/ _ \    / /\ \  \___ \| |      | |   | |
#    | |  __/>  <| |_  | || (_) |  / ____ \ ____) | |____ _| |_ _| |_
#    |_|\___/_/\_\\__|  \__\___/  /_/    \_\_____/ \_____|_____|_____|
#
#   http://patorjk.com/software/taag/#p=display&f=Big&t=Home-Assistant

